pdf-rs/pdf

Cargo.toml
https://github.com/pdf/pdf-rs doesn't exist  ;)
=> Cargo.toml: Fix URL in package.repository

Cargo.toml, src/err.rs, src/lib.rs
This PR fixes build errors with rustc v1.33.0
It introduces a workaround to tackle an issue that originates in error_chain.
It removes feature flags, that are already implemented at this point in time.
=> Fix build errors with rustc v1.33.0

src/parser/lexer/str.rs
This fills in a couple unimplemented match branches.
=> Handle \b and \f in strings

src/xref.rs
When comparing generation numbers of XRef entries, the wrong index was
being used to look up the existing entry's generation number.
=> Fix XRefTable updates

Cargo.toml, src/backend.rs, src/lib.rs, src/object/stream.rs
There are a couple print statements in the library that write to stdout and stderr when opening a file. This PR pulls in the `log` crate and changes those lines to use `trace!()`, so that clients can choose whether and how to get log messages.
=> Use the log crate in lieu of println/eprintln

src/backend.rs
When attempting to open a corrupt file, read_xref_table_and_trailer may
try to read past the end of the file. This results in a Range with its
end before its start, and the library panics when slicing the underlying
data. This change checks for such cases, and returns an error instead of
panicking.
=> Add bounds checks to backends

pdf/src/crypt.rs, pdf/src/enc.rs, pdf/src/encoding/mod.rs, pdf/src/file.rs, pdf/src/font.rs, pdf/src/object/stream.rs, pdf/src/object/types.rs, pdf_derive/src/lib.rs
This PR adjusts the paths used in pdf_derive's macro, so that it can be used from other crates again. Instead of using module paths that start with `crate::`, which won't work in crates other than pdf, this uses paths that start with `pdf::`, and adds `use crate as pdf;` to the files in pdf where it is used.
=> Make pdf_derive usable from other crates

pdf/src/file.rs
I'd like to parse a PDF file and read dictionaries other than those currently defined in `Catalog`. To do so, it looks like I'll need access to Storage, so I'd like to make it, and its factory method, public.
=> Make Storage and Storage::new public

.gitignore, README.md, download_fonts.sh
Here's a bash script to simplify downloading and extracting fonts from the Adobe Reader deb file. (follow-up to #50)
=> Add script to download and extract fonts

Cargo.toml, examples/metadata/Cargo.toml, examples/metadata/src/main.rs
I'm curious if there are other kinds of metadata inside PDFs. I stole
this logic from examples/read/src/main.rs.
Partly address #31.
=> add an example to print metadata

pdf/src/backend.rs, pdf/src/content.rs, pdf/src/crypt.rs, pdf/src/enc.rs, pdf/src/encoding.rs, pdf/src/error.rs, pdf/src/font.rs, pdf/src/object/color.rs, pdf/src/object/function.rs, pdf/src/object/mod.rs, pdf/src/object/stream.rs, pdf/src/object/types.rs, pdf/src/parser/lexer/mod.rs, pdf/src/parser/lexer/str.rs, pdf/src/parser/parse_object.rs, pdf/src/parser/parse_xref.rs, pdf/src/primitive.rs, pdf/src/xref.rs
Contains one breaking change, namely renaming `Primitive::to_*` function to `Primitive::into_*` because they take `self`.
Next I'm not sure about these
```
warning: unused variable: `ctx`
--> pdf/src/parser/mod.rs:196:65
|
196 | fn parse_stream_with_lexer(lexer: &mut Lexer, r: &impl Resolve, ctx: Option<&Context>) -> Result<PdfStream> {
|                                                                 ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`
|
= note: `#[warn(unused_variables)]` on by default
warning: unused variable: `params`
--> pdf/src/enc.rs:196:28
|
196 | fn dct_decode(data: &[u8], params: &DCTDecodeParams) -> Result<Vec<u8>> {
|                            ^^^^^^ help: if this is intentional, prefix it with an underscore: `_params`
```
Whether the …
=> Fix most warnings and clippy

files/offset.pdf, pdf/src/backend.rs, pdf/src/file.rs, pdf/src/repair.rs
This PR fixes parsing PDF files where the header is not at offset 0 in the file. In such cases, the offsets in the trailer and xref tables should be interpreted as offsets from the header, and not offsets from the beginning of the underlying file. See mozilla/pdf.js#6194 for a similar issue in pdf.js. I found a file exhibiting this behavior in the wild at https://iaspub.epa.gov/otaqpub/display_file.jsp?docid=50126&flag=1.
There is one TODO outstanding in this PR, so I'll mark it as a draft. Currently, the code searches the beginning of the file for the header's position in multiple places, but I'd like to find a way to compute this once and reuse it. The header offset is needed in both `Backend::read_xref_table_and_trailer(&self)` and `<Storage<B: Backend> as Resolve>::resolve(&self, r: …
=> Make xref offsets relative to file header

pdf/src/error.rs, pdf/src/parser/lexer/mod.rs
This PR makes the PdfError type both Send and Sync, by adding trait bounds to the trait objects it contains, and generic types in a couple functions that produce them. I also added a compile-time assertion for this to catch any future regressions.
=> Make PdfError Send and Sync

pdf/src/parser/mod.rs
This PR makes a small change to allow empty arrays. A unit test is included.
=> Fix parsing of empty arrays

pdf/src/crypt.rs
Decrypt the empty string to itself, and return an error rather than panicking when there is not enough data for the IV.
I ran into this in the wild on http://cdn01.foxitsoftware.com/pub/foxit/addonservice/certs/phantom/cer.pdf (password: phantomkey) which uses AESV3. Since the specification of AESV3 hasn't been released, it's impossible to say if empty strings should in fact be decrypted to empty strings, or if this file is improperly constructed, but I figure it's safe enough to just do so.
=> Gracefully handle too-short strings in AESV2/AESV3

pdf/src/parser/lexer/str.rs
The character code is calculated as u16 to prevent panics on
overflow which is then ignored.
=> Fix parsing of octal escape sequences

pdf/src/object/types.rs
This fixes a couple types related to embedded files. `/EmbeddedFiles` in the name dictionary should be a name tree, and /F, /UF, /DOS, /Mac, and /Unix inside /EF should be streams.
=> Fix types in /EmbeddedFiles

pdf_derive/Cargo.toml, pdf_derive/src/lib.rs
As described in dtolnay/syn@957840e, using syn::export was always discouraged and has now become a breaking change.
This patched was heavily inspired by nushell/nushell#2867.
Happy Hacking! :keyboard:
=> Fix syn 1.0.58 breaking compilation of pdf_derive

pdf/src/crypt.rs, pdf/src/file.rs
As discussed [in #77](https://github.com/pdf-rs/pdf/pull/77/#issuecomment-780983898]), this fixes support of files with `/EncryptMetadata false`. I tested it on the linked file from ETSI, and this fixes the decryption/unpadding error.
=> Handle /EncryptMetadata properly

pdf/src/object/types.rs
Small typo I noticed, `"LC" => "LJ"`
=> Fix key for line join style

pdf/Cargo.toml, pdf/src/enc.rs
This fixes an advisory warning since lzw is unmaintained for quite some
time now. The new implementation is also quite a lot faster, mostly for
the (currently unused) encoding. See also: https://github.com/J-F-Liu/lopdf/pull/140
=> Replace lzw with weezl

files/formxobject.pdf, pdf/src/object/types.rs
This branch parses dictionaries of Form XObjects.
Currently, such the following FormXObjects are stored in `Content`.
This branch adds some attributes to `FormDict` to hold resources and other information.
```
5 0 obj
<< /Subtype /Form
/Type /XObject
/FormType 1
/Resources << /Font << /F0 6 0 R >> >>
/BBox [0 0 180 240]
/Length 47
>>
stream
BT
/F0 24 Tf
25.68 200 Td
(Hello World!) Tj
ET
endstream
endobj
```
This branch uses `Stream<FormDict>`, so stream data can be retrieved using `data()` function.
`Stream<I>` is useful for retrieving raw binary data such as image data.
But I couldn't find good solutions for converting it to `Content`. Is there good idea?
=> Support meta data of Form XObject

pdf/src/content.rs
This is a partial fix for #90, see [the discussion there](https://github.com/pdf-rs/pdf/issues/90#issuecomment-853527020). `<ContentStream as Object>::from_primitive` needs a small tweak to handle indirect objects that are arrays of streams.
=> Handle /Contents being an indirect array

pdf/src/content.rs
Please check my matrix math. It's been quite a while since I did first-year engineering maths.
Default matrix implementation yields the identity matrix.
=> Add Default implementations for Matrix and Point

pdf/src/parser/lexer/mod.rs, pdf/tests/xref.rs
I'm not sure what the `// TODO +- 1` means, does this fix whatever the comment was about?
=> Fix index OOB when file ends with angle bracket

pdf/fuzz/.gitignore, pdf/fuzz/Cargo.toml, pdf/fuzz/fuzz_targets/parse.rs
This uses https://github.com/rust-fuzz/cargo-fuzz in order to generate random (likely invalid) PDFs, and then tries to parse them.
It's a good way to find invalid inputs that cause panics. I'll make pull requests with test cases for the issues that I find using it, but you should also probably set it up to find bugs.
=> Add fuzzing harness

pdf/Cargo.toml
Just been doing some spring cleaning on some project dependencies and it looks like there were a couple of unused dependencies in the `pdf` crate along with `glob` being used just for tests
=> Remove and move unused dependencies

pdf/Cargo.toml
So it's not an issue on [the crates.io page](https://crates.io/crates/pdf), but it looks like [the lib.rs page](https://lib.rs/crates/pdf) won't link to the repository unless it appears to be a valid repo. Instead it looks like it falls back to linking to the source files stored on docs.rs.
This change just updates the link in the `pdf` crate to point to the pdf repo instead of the pdf-rs org
=> Point pdf crate link to repository

pdf/examples/content.rs, pdf/examples/read.rs, pdf/examples/text.rs, pdf/src/content.rs, pdf/src/crypt.rs, pdf/src/enc.rs, pdf/src/font.rs, pdf/src/object/function.rs, pdf/src/object/mod.rs, pdf/tests/integration.rs
These aren't all necessarily the best fixes (and I've left a few TODOs in places that seem like good candidates for a better fix), but it gets the code to a state where you can build and run clippy without any warnings or lints, which is helpful to avoid accidentally introducing new ones.
=> Fix or disable warnings and lints

pdf/Cargo.toml, pdf/examples/metadata.rs, pdf/examples/names.rs, pdf/examples/read.rs, pdf/src/error.rs, pdf/src/font.rs, pdf/src/primitive.rs
- avoid extra allocations decoding utf-16be
- deprecated PdfString::as_str()
- removed dependencies, utf16be decoding can be done with pdf-lib only now
=> Remove pdfstring as str

pdf/Cargo.toml
`memmap` hasn't been maintained for a while (https://github.com/danburkert/memmap-rs/issues/90). `memmap2` currently exists as an actively maintained fork instead
`memmap` not being maintained doesn't seem too pressing, but it does get flagged by `cargo audit` for being unmaintained
=> Switch out `memmap` for `memmap2`

pdf/src/content.rs
I'm using this library for quire some time, and finally decided to merge latest changes. pdfs (invoices) that used to parse just fine suddenly started crashing, this makes all my test cases pass again
=> fix unnecessary panic on poorly formatted pdf haha

pdf/src/parser/lexer/mod.rs
Hey, another one which fixes 2 invoices in my test-base. The way I see it is that is that behavior is identical, minus the panic (which allows any kind of recovery). I leave this to your judgement, becuase I don't handle any inline images in my code (they are there though since parsing them panics at this specific line).
=> fix unnecessary panic with inline image

pdf/src/font.rs
I came across this when fetching widths of a font. This PR:
- Checks for underflow, does not increase capacity,
- Uses the correct capacity numbers (`cid - first_char` is offset index)
=> Check for underflow in `ensure_cid`

pdf/src/object/types.rs
Came across this bug where the original filters slice is passed through instead of the `image_filters`.
=> Fix bug where compression filters are passed through as image filters

pdf/src/content.rs, pdf/src/error.rs, pdf/src/object/types.rs
Resolves an error encountered parsing PDF file sample01.pdf from
https://github.com/sambitdash/PDFTest/tree/master/DigSig
Try { file: "pdf/src/file.rs", line: 324, column: 23, context: Context([]), source: FromPrimitive { typ: "RcRef < Catalog >", field: "root", source: Shared { source: FromPrimitive { typ: "Option < MaybeRef < NameDictionary > >", field: "names", source: Shared { source: FromPrimitive { typ: "Option < NameTree < Primitive > >", field: "ids", source: UnexpectedPrimitive { expected: "String", found: "Reference" } } } } } } }
=> Fix parsing of NameTree<Primitive> type by optionally dereferencing.

pdf/src/enc.rs
I have a PDF with images using the DCTDecode filter for their masks, which would previously cause errors when attempting to extract them (using code like that in `pdf_render`). It seems like this might have just been a minor point that was missed in previous work because after this one-line change to add a match clause, I can successfully extract images and their masks from that PDF and have verified that they seem to be read as expected.
=> Add support for StreamFilter::DCTDecode

pdf/src/crypt.rs, pdf/src/file.rs
This pull request fixes the following:
* When opening encrypted pdfs with 128 bit keys, pdf-rs paniced because of missing range checks.
* The encryption was not properly applied to streams which lead to panics when LZW Decompress was applied to encrypted data.
=> fix panics on opening encrypted pdfs

pdf/examples/names.rs, pdf/examples/read.rs, pdf/src/font.rs, pdf/src/primitive.rs
Function utf16be_tu_string_lossy always returns an Ok(..) result, as its name suggests. Therefore wrapping in a Result<_> is unnecessary. Bubbles up to PdfString::to_string_lossy.
=> Let utf16be_to_string_lossy return a String directly

pdf/src/enc.rs
In an error handling branch some data is written to /tmp/data (presumably for debugging). This causes a write error on windows, obscuring the actual error. This could be done using the `tempfile` crate to be cross platform but it's probably better just to remove the call as it's not used by the library itself.
=> Don't write to /tmp/data

pdf/src/encoding.rs
USGS GeoTopo PDFs stash font data in Streams.  Here we patch the stream info dictionary into the processing feed instead of panic'ing.
=> Support stream types in creating encoding

examples/src/bin/add_image.rs
The CLI doc comments that clap also uses to generate a --help interface was wrong and undescriptive.
I've changed them so they reflect their actual use in the example program.
=> fix typo in example CLI doc comments

pdf/examples/content.rs, pdf/examples/metadata.rs, pdf/examples/names.rs, pdf/examples/other_page_content.rs, pdf/examples/read.rs, pdf/tests/integration.rs
Not sure this is the proper fix, but submitting just in case it is
Fixes errors like:
```
error[E0599]: no function or associated item named `cached` found for struct `FileOptions` in the current scope
--> examples/content.rs:13:33
|
13 |     let mut file = FileOptions::cached().open(&path).unwrap();
|                                 ^^^^^^
|                                 |
|                                 function or associated item not found in `FileOptions<'_, _, _>`
|                                 help: there is a method with a similar name: `cache`
For more information about this error, try `rustc --explain E0599`.
error: could not compile `pdf` due to previous error
```
Used to fail with:
`cargo test --all-targets --no-default-features --features dump`
`cargo test --all-targets …
=> fix build failure when running tests without cache feature

pdf/examples/read.rs
Tested with a PDF scanned with a single bit per pixel black and white as the color space.
the resulting tiff could be opened in GIMP and Windows default app (Preview).
This is as discussed in #206. I do not think this will fix that issue as it does not address png images.
=> Expand the pdf/examples/read to extract processable tiff files

pdf/src/object/types.rs
Hello ! 
I like your crate, but I found a bug in the InfoDict parser: when trying to get the producer in the InfoDict, it returned me the Author instead. 
The parser parsed the wrong key, probably a typo.
=> fix InfoDict producer

pdf/src/font.rs
If the number of bytes in the stream is odd, indexing c[1] will result in an out of bounds access and will cause a panic.
This should not happen normally, since the spec says that this field should be a list of u16, but some malformed PDF trigger this bug.
This patch just ignores the last byte of odd length CidToGid tables, but we could check for odd lengths and return an error instead. Tell me what you prefer in this case.
=> fix panic on malformed CIDToGID tables

pdf/src/crypt.rs
Found this bug while fuzzing the crate. The spec says that /Length must be a multiple of 8 bits, but Decoder::from_password doesn't check for it, and panics if a length of 5 is passed.
Return an error if the key length is not a multiple of 8 bits.
=> fix panic on 5 bits encryption key

pdf/src/crypt.rs
Found this bug while fuzzing the crate.
The spec says that in the ecryption dictonary, /Length is the length of the key, and should be between 40 to 128 bits. However, if we specify 256 the parser still accepts it but panics in Decoder::decrypt() while performing the b) step.
The b) step is implemented by truncating the key length to a maximum of 128 bits (16 bytes) before concatenating the object number and generation of the string being decrypted.
However, while computing the size of n, Decoder::decode() does not truncate the key size to 16, and this leads to an out of bound panic.
Note that I can't find the reason for this trucation to 16 bytes in the b) step. The spec does require truncating the key to 16 bytes, but that's in the d) step which is where we truncate the resulting hash. …
=> fix panic on 256 bits RC4 keys

pdf/src/file.rs
Found this bug by fuzzing.
If the trailer ID is an empty array, `load_storage_and_trailer_password()` will panic when trying to access the first byte of an encrypted document.
Note that shouldn't happen on valid documents, the ID is supposed to be a an array of two byte strings.
=> fix panic on malformed trailer ID

pdf/src/content.rs
The dash operator is serialized incorrectly to the content stream.
=> fix: Fixed dash operator serialization

pdf/src/object/types.rs
Fix for `resolver().get()` failing with following error when resolving a `Ref<Stream<EmbeddedFile>>`, if a `CheckSum` field is present:
Shared, caused by
Can't parse field params of struct Option < EmbeddedFileParamDict >, caused by
Can't parse field checksum of struct Option < Date >, caused by
Failed parsing date
ChekSum is defined as [16-byte string](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf), so `PdfString` should be a more fitting type.
=> Fixed wrongly typed checksum field in EmbeddedFileParamDict

pdf/src/object/types.rs
When I parsed annotations of pdf, found some missing keys of annot
=> Fix annotation missing keys in Annot Struct

pdf/src/enc.rs
Found this bug while fuzzing the crate
The range of values that an ascii85 character can take is slightly bigger than what fits in a u32. If `a`, `b`, `c`, `d`, and `e` are very high, the multiplication will result in a number that cannot be represented as a u32. This should be considered as a decoding error, but the code didn't check for this case and panicked.
Do the computation in a u64 instead, and try to cast it to a u32 at the very end, returning None if the value is invalid.
=> fix panic on overflowing ascii85 decode
